### ISSUE TITLE
NPMplus not starting (Develop)

### ISSUE THREAD

**Issue by shedowe19** [ZoeyVid/NPMplus#1302]
```
[Global   ] › ✖  error     Error relocating /app/node_modules/better-sqlite3/build/Release/better_sqlite3.node: _ZN2v89Exception10RangeErrorENS_5LocalINS_6StringEEENS1_INS_5ValueEEE: symbol not found Error: Error relocating /app/node_modules/better-sqlite3/build/Release/better_sqlite3.node: _ZN2v89Exception10RangeErrorENS_5LocalINS_6StringEEENS1_INS_5ValueEEE: symbol not found
    at Module._extensions..node (node:internal/modules/cjs/loader:1454:18)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at bindings (/app/node_modules/bindings/bindings.js:112:48)
    at new Database (/app/node_modules/better-sqlite3/lib/database.js:48:64)
    at Client_BetterSQLite3.acquireRawConnection (/app/node_modules/knex/lib/dialects/better-sqlite3/index.js:14:12)
    at create (/app/node_modules/knex/lib/client.js:262:39) {
  code: 'ERR_DLOPEN_FAILED'
}
[Global   ] › ✖  error     Error relocating /app/node_modules/better-sqlite3/build/Release/better_sqlite3.node: _ZN2v89Exception10RangeErrorENS_5LocalINS_6StringEEENS1_INS_5ValueEEE: symbol not found Error: Error relocating /app/node_modules/better-sqlite3/build/Release/better_sqlite3.node: _ZN2v89Exception10RangeErrorENS_5LocalINS_6StringEEENS1_INS_5ValueEEE: symbol not found
    at Module._extensions..node (node:internal/modules/cjs/loader:1454:18)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at bindings (/app/node_modules/bindings/bindings.js:112:48)
    at new Database (/app/node_modules/better-sqlite3/lib/database.js:48:64)
    at Client_BetterSQLite3.acquireRawConnection (/app/node_modules/knex/lib/dialects/better-sqlite3/index.js:14:12)
    at create (/app/node_modules/knex/lib/client.js:262:39) {
  code: 'ERR_DLOPEN_FAILED'
}
[Global   ] › ✖  error     Error relocating /app/node_modules/better-sqlite3/build/Release/better_sqlite3.node: _ZN2v89Exception10RangeErrorENS_5LocalINS_6StringEEENS1_INS_5ValueEEE: symbol not found Error: Error relocating /app/node_modules/better-sqlite3/build/Release/better_sqlite3.node: _ZN2v89Exception10RangeErrorENS_5LocalINS_6StringEEENS1_INS_5ValueEEE: symbol not found
    at Module._extensions..node (node:internal/modules/cjs/loader:1454:18)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at bindings (/app/node_modules/bindings/bindings.js:112:48)
    at new Database (/app/node_modules/better-sqlite3/lib/database.js:48:64)
    at Client_BetterSQLite3.acquireRawConnection (/app/node_modules/knex/lib/dialects/better-sqlite3/index.js:14:12)
    at create (/app/node_modules/knex/lib/client.js:262:39) {
  code: 'ERR_DLOPEN_FAILED'
}
[Global   ] › ✖  error     Error relocating /app/node_modules/better-sqlite3/build/Release/better_sqlite3.node: _ZN2v89Exception10RangeErrorENS_5LocalINS_6StringEEENS1_INS_5ValueEEE: symbol not found Error: Error relocating /app/node_modules/better-sqlite3/build/Release/better_sqlite3.node: _ZN2v89Exception10RangeErrorENS_5LocalINS_6StringEEENS1_INS_5ValueEEE: symbol not found
    at Module._extensions..node (node:internal/modules/cjs/loader:1454:18)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at bindings (/app/node_modules/bindings/bindings.js:112:48)
    at new Database (/app/node_modules/better-sqlite3/lib/database.js:48:64)
    at Client_BetterSQLite3.acquireRawConnection (/app/node_modules/knex/lib/dialects/better-sqlite3/index.js:14:12)
    at create (/app/node_modules/knex/lib/client.js:262:39) {
  code: 'ERR_DLOPEN_FAILED'
}
```

**Comment by Zoey2936** [comment]
Arm64 or x86-64?

**Comment by shedowe19** [comment]
x86-64

**Comment by Zoey2936** [comment]
can you please try again now?

**Comment by Zoey2936** [comment]
it should work, if not please reopen this

**Comment by Zoey2936** [comment]
just to let you know, the develop build should be broken in big parts
