### ISSUE TITLE
Failed to get SSL from certbot

### ISSUE THREAD

**Issue by afzl-wtu** [ZoeyVid/NPMplus#337]
Update: I tried after 1 hour and now all my websites are with SSL.

I recently wiped my server and created new instance with new ip. point my dns to new ip. Earlier I was using jc21 NPM. Now I installed your one. Everything works fine. But I can not get SSL on my website.. Earlier attempts were failed because of firewalld blocking 80 and 443 ports. Now I added them to allow list. Now I can access my website through http but I can not git it working with SSL. Here is container log:
```
Server: nginx
Date: Mon, 17 Jul 2023 18:45:26 GMT
Content-Type: application/json
Content-Length: 1055
Connection: keep-alive
Boulder-Requester: 1211435507
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 15C9Fi9emmjENdUcH-2OxLuHO1S3Q0tfbPm2FS_Fw_35TaM
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "proxy.afzal.website"
  },
  "status": "invalid",
  "expires": "2023-07-24T18:45:25Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "invalid",
      "error": {
        "type": "urn:ietf:params:acme:error:connection",
        "detail": "138.2.138.227: Fetching http://proxy.afzal.website/.well-known/acme-challenge/r1oBTyCuUTp9vaVUYs58Nsd6W71yfORGk59Ht6YBSUc: Error getting validation data",
        "status": 400
      },
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/246483032907/RW8POA",
      "token": "r1oBTyCuUTp9vaVUYs58Nsd6W71yfORGk59Ht6YBSUc",
      "validationRecord": [
        {
          "url": "http://proxy.afzal.website/.well-known/acme-challenge/r1oBTyCuUTp9vaVUYs58Nsd6W71yfORGk59Ht6YBSUc",
          "hostname": "proxy.afzal.website",
          "port": "80",
          "addressesResolved": [
            "138.2.138.227"
          ],
          "addressUsed": "138.2.138.227"
        }
      ],
      "validated": "2023-07-17T18:45:25Z"
    }
  ]
}
2023-07-17 23:45:26,682:DEBUG:acme.client:Storing nonce: 15C9Fi9emmjENdUcH-2OxLuHO1S3Q0tfbPm2FS_Fw_35TaM
2023-07-17 23:45:26,682:INFO:certbot._internal.auth_handler:Challenge failed for domain proxy.afzal.website
2023-07-17 23:45:26,682:INFO:certbot._internal.auth_handler:http-01 challenge for proxy.afzal.website
2023-07-17 23:45:26,682:DEBUG:certbot._internal.display.obj:Notifying user: 
Certbot failed to authenticate some domains (authenticator: webroot). The Certificate Authority reported these problems:
  Domain: proxy.afzal.website
  Type:   connection
  Detail: 138.2.138.227: Fetching http://proxy.afzal.website/.well-known/acme-challenge/r1oBTyCuUTp9vaVUYs58Nsd6W71yfORGk59Ht6YBSUc: Error getting validation data

Hint: The Certificate Authority failed to download the temporary challenge files created by Certbot. Ensure that the listed domains serve their content from the provided --webroot-path/-w and that files created there can be downloaded from the internet.

2023-07-17 23:45:26,683:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/usr/local/certbot/lib/python3.11/site-packages/certbot/_internal/auth_handler.py", line 108, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, max_time_mins, best_effort)
  File "/usr/local/certbot/lib/python3.11/site-packages/certbot/_internal/auth_handler.py", line 212, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.

2023-07-17 23:45:26,683:DEBUG:certbot._internal.error_handler:Calling registered functions
2023-07-17 23:45:26,683:INFO:certbot._internal.auth_handler:Cleaning up challenges
2023-07-17 23:45:26,683:DEBUG:certbot._internal.plugins.webroot:Removing /tmp/acme-challenge/.well-known/acme-challenge/r1oBTyCuUTp9vaVUYs58Nsd6W71yfORGk59Ht6YBSUc
2023-07-17 23:45:26,684:DEBUG:certbot._internal.plugins.webroot:All challenges cleaned up
2023-07-17 23:45:26,684:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/certbot/bin/certbot", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/certbot/lib/python3.11/site-packages/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/certbot/lib/python3.11/site-packages/certbot/_internal/main.py", line 1864, in main
    return config.func(config, plugins)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/certbot/lib/python3.11/site-packages/certbot/_internal/main.py", line 1597, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/certbot/lib/python3.11/site-packages/certbot/_internal/main.py", line 141, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/certbot/lib/python3.11/site-packages/certbot/_internal/client.py", line 517, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/certbot/lib/python3.11/site-packages/certbot/_internal/client.py", line 428, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/certbot/lib/python3.11/site-packages/certbot/_internal/client.py", line 496, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, self.config, best_effort)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/certbot/lib/python3.11/site-packages/certbot/_internal/auth_handler.py", line 108, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, max_time_mins, best_effort)
  File "/usr/local/certbot/lib/python3.11/site-packages/certbot/_internal/auth_handler.py", line 212, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.
2023-07-17 23:45:26,685:ERROR:certbot._internal.log:Some challenges have failed.
/tmp/certbot-log # 
```

**Comment by Zoey2936** [comment]
so it works now?

**Comment by afzl-wtu** [comment]
> so it works now?

Ofcourse
