### ISSUE TITLE
add option to disable nginx beautifier

### ISSUE THREAD

**Issue by realies** [ZoeyVid/NPMplus#936]
e.g. `DISABLE_NGINX_BEAUTIFIER`;

blocks like this:
```
        location / {
            access_by_lua_block {
                local http = require("resty.http")

                local target_ip = "192.168.0.1"
                local target_port = 8080
                local mac_address = "aa:bb:cc:dd:ee:ff"

                local httpc = http.new()
                httpc:set_timeout(1000)  -- 1 second timeout

                local res, err = httpc:request_uri("http://" .. target_ip .. ":" .. target_port, {method = "HEAD"})

                if not res then
                    ngx.log(ngx.NOTICE, "Target is not responding, attempting to send WoL packet")
                    local command = string.format("wakeonlan %s", mac_address)
                    local success = os.execute(command)
                    if success then
                        ngx.log(ngx.NOTICE, "Sent WoL packet to " .. mac_address)
                        ngx.sleep(30)
                    else
                        ngx.log(ngx.ERR, "Failed to send WoL packet")
                    end
                else
                    ngx.log(ngx.NOTICE, "Target is already responsive")
                end
            }

            proxy_pass http://192.168.0.1:8080;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
        }

```

cause:
```
npmplus  | /usr/local/share/.config/yarn/global/node_modules/nginxbeautifier/nginxbeautifier.js:142
npmplus  |         return input.match(catchRegex)[1];
npmplus  |                                       ^
npmplus  | 
npmplus  | TypeError: Cannot read properties of null (reading '1')
npmplus  |     at extractTextBySeperator (/usr/local/share/.config/yarn/global/node_modules/nginxbeautifier/nginxbeautifier.js:142:39)
npmplus  |     at extractAllPossibleText (/usr/local/share/.config/yarn/global/node_modules/nginxbeautifier/nginxbeautifier.js:164:29)
npmplus  |     at strip_line (/usr/local/share/.config/yarn/global/node_modules/nginxbeautifier/nginxbeautifier.js:193:35)
npmplus  |     at Object.clean_lines (/usr/local/share/.config/yarn/global/node_modules/nginxbeautifier/nginxbeautifier.js:225:50)
npmplus  |     at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/nginxbeautifier/index.js:235:38)
npmplus  |     at Module._compile (node:internal/modules/cjs/loader:1358:14)
npmplus  |     at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
npmplus  |     at Module.load (node:internal/modules/cjs/loader:1208:32)
npmplus  |     at Module._load (node:internal/modules/cjs/loader:1024:12)
npmplus  |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
npmplus  | 
npmplus  | Node.js v20.13.1
```

**Comment by Zoey2936** [comment]
Hello, if you want you can create a PR, if not then I will add this env next week

**Comment by realies** [comment]
@Zoey2936 just noticed running the container without PUID/PGID (root) does not cause this issue for some reason

**Comment by Zoey2936** [comment]
Hello, this doesn't make sense because the userswitch happens after nginx beautifier: https://github.com/ZoeyVid/NPMplus/blob/ada2fe3c13eed2c06f5f82b0aef7ad31e0864224/rootfs/usr/local/bin/start.sh#L945

**Comment by realies** [comment]
you're right; i've actually modified this slightly, the issue was coming from lack of spaces around the curly braces
```diff
-      local res, err = httpc:request_uri("http://" .. target_ip .. ":" .. target_port, {method = "HEAD"})
+      local res, err = httpc:request_uri("http://" .. target_ip .. ":" .. target_port, { method = "HEAD" })
```
